# Generated by Django 3.2.6 on 2021-09-09 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('project_id', models.CharField(help_text='项目id', max_length=30, primary_key=True, serialize=False, verbose_name='项目编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('company', models.CharField(help_text='客户', max_length=50, verbose_name='客户名称')),
                ('budget', models.DecimalField(decimal_places=2, help_text='项目预算', max_digits=20, verbose_name='项目预算')),
                ('get_percent', models.DecimalField(decimal_places=2, help_text='中标概率', max_digits=5, verbose_name='中标概率')),
                ('customer', models.CharField(help_text='客户代表', max_length=25, verbose_name='客户代表')),
                ('tel', models.CharField(help_text='客户联系方式', max_length=25, verbose_name='联系方式')),
                ('sales_department', models.ForeignKey(blank=True, help_text='销售部门', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user_app.department', verbose_name='销售部门')),
                ('salesman', models.ForeignKey(blank=True, help_text='销售人员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'sky_projects',
                'ordering': ['create_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_issue', models.TextField(help_text='进度信息', verbose_name='进度信息')),
                ('project_id', models.ForeignKey(blank=True, help_text='项目编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='project_app.projects', verbose_name='项目编号')),
            ],
            options={
                'verbose_name': '项目进度',
                'verbose_name_plural': '项目进度',
                'db_table': 'sky_processes',
            },
        ),
        migrations.CreateModel(
            name='BidsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, '投标中'), (1, '已中标'), (2, '未中标'), (3, '其他')], help_text='投标状态', max_length=20, verbose_name='投标状态')),
                ('money', models.DecimalField(decimal_places=2, help_text='中标金额', max_digits=10, verbose_name='中标金额')),
                ('status_desc', models.TextField(help_text='状态信息', verbose_name='状态信息')),
                ('department', models.ForeignKey(blank=True, help_text='商务部门', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_info', to='user_app.department', verbose_name='商务部门')),
                ('project_id', models.ForeignKey(blank=True, help_text='项目id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_info', to='project_app.projects', verbose_name='项目id')),
                ('shangwu', models.ForeignKey(blank=True, help_text='商务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_info', to=settings.AUTH_USER_MODEL, verbose_name='商务')),
            ],
            options={
                'verbose_name': '投标信息',
                'verbose_name_plural': '投标信息',
                'db_table': 'sky_bids_info',
            },
        ),
    ]
