# Generated by Django 3.2.6 on 2021-09-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '投标中'), (1, '已中标'), (2, '未中标'), (3, '其他')], help_text='投标状态', max_length=20, verbose_name='投标状态'),
        ),
    ]
