# Generated by Django 3.2.6 on 2021-09-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='合同编号', max_length=50, verbose_name='合同编号')),
                ('name', models.CharField(help_text='合同名称', max_length=50, verbose_name='合同名称')),
                ('money', models.DecimalField(decimal_places=2, help_text='合同金额', max_digits=20, verbose_name='合同金额')),
                ('buyer', models.CharField(help_text='客户名称', max_length=25, verbose_name='客户名称')),
                ('contact_man', models.CharField(help_text='联系人', max_length=25, verbose_name='联系人')),
                ('contact_way', models.CharField(help_text='练习方式', max_length=25, verbose_name='联系方式')),
                ('sign_at', models.DateTimeField(auto_now_add=True, help_text='签订时间', verbose_name='签订时间')),
                ('is_accepted', models.CharField(choices=[(0, '未验收'), (1, '已验收')], help_text='交货验收', max_length=20, verbose_name='交货验收')),
                ('accepted_info', models.TextField(help_text='验收信息', verbose_name='验收信息')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'db_table': 'sky_contracts',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(choices=[(0, '现金'), (1, '股票'), (2, '抵押'), (3, '货物交换')], help_text='货款方式', max_length=20, verbose_name='回款方式')),
                ('pay_message', models.TextField(help_text='备注', verbose_name='备注')),
                ('need_pay', models.DecimalField(decimal_places=2, help_text='待收款', max_digits=20, verbose_name='待收款')),
                ('already_pay', models.DecimalField(decimal_places=2, help_text='回款', max_digits=20, verbose_name='回款')),
                ('pay_time', models.DateTimeField(help_text='回款时间', verbose_name='回款时间')),
                ('contract_id', models.ForeignKey(blank=True, help_text='合同编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_info', to='contract_app.contract', verbose_name='合同编号')),
            ],
            options={
                'verbose_name': '回款信息',
                'verbose_name_plural': '回款信息',
                'db_table': 'sky_pay_info',
            },
        ),
    ]
