# Generated by Django 3.2.6 on 2021-09-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_accepted',
            field=models.SmallIntegerField(choices=[(0, '未验收'), (1, '已验收')], help_text='交货验收', max_length=20, verbose_name='交货验收'),
        ),
    ]
